name: dart_generator_test
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.0-358.0.dev <3.0.0'

dependencies:
  logger:
  meta:
#  path: ^1.7.0


dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.15   # build_runner >=0.10.1 depends on web_socket_channel ^1.0.9 and test >=1.16.6 depends on web_socket_channel ^2.0.0, build_runner >=0.10.1 is incompatible with test >=1.16.6.
  build_runner: ^1.10.11