name: dart_generator_test
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^2.16.0-80.0.dev

dependencies:
  logger:
  meta:

dev_dependencies:
  pedantic:
  test:
  build_runner: